[build]
builder = "DOCKERFILE"
dockerfilePath = "flask-api/Dockerfile"
dockerContext = "."

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
