[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.prod.yml"

[deploy]
startCommand = "docker-compose -f docker-compose.prod.yml up"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
